Repository boostcampwm-2021/web04-canyoufixme, pull requests merged in 2021-12, with the labels that each got.

#171 chore: 타입 빌드명령 추가 및 esbuild 적용을 통한 빌드 최적화
  Dockerfile
  package.json
  packages/frontend/craco.config.js
  packages/frontend/package.json
  packages/frontend/src/components/Modal/GuideModal.tsx
  packages/frontend/src/components/Modal/ModalType.ts
  packages/frontend/src/pages/EditorPage/index.tsx
  packages/frontend/src/pages/IntroPage/index.tsx
  packages/frontend/src/pages/WriteEditorPage/index.tsx
  yarn.lock
Labels: 버그 🐛, 개선 📈, 배포 🚀

#174 fix: debounce 패키지를 제거하고 throttle 패키지 추가
  Dockerfile
  packages/debounce/examples/index.html
  packages/debounce/examples/index.js
  packages/debounce/index.d.ts
  packages/debounce/index.js
  packages/debounce/package.json
Labels: 중요도: 최상, 배포 🚀

#173 fix: 무한스크롤 무한 로딩 및 화면 크기에 따라 정상 기능 안하던 오류 수정
  packages/frontend/src/pages/ListPage/index.tsx
  packages/frontend/src/pages/ListPage/message.ts
  packages/frontend/src/pages/ListPage/reducer.ts
Labels: 버그 🐛, 프론트엔드 ⚛️

#175 feat: 테스트케이스 가이드라인 페이지에 chai 공식 문서 링크 추가
  packages/frontend/src/assets/images/chai.png
  packages/frontend/src/pages/GuidePage/constant.ts
  packages/frontend/src/pages/GuidePage/index.tsx
  packages/frontend/src/pages/GuidePage/message.ts
Labels: 개선 📈, 프론트엔드 ⚛️

#176 fix: 누락된 React import 추가
  packages/frontend/src/components/GitHubLoginButton/index.tsx
  packages/frontend/src/components/ResultViewer.tsx
  packages/frontend/src/pages/GuidePage/index.tsx
  packages/frontend/src/pages/NotFoundPage/index.tsx
Labels: 버그 🐛

#177 feat: 통계 데이터를 보여주는 로직에 Intersection Observer API 적용
  packages/frontend/src/pages/IntroPage/index.tsx
  packages/frontend/src/pages/IntroPage/message.ts
  packages/frontend/src/pages/IntroPage/reducer.ts
Labels: 개선 📈, 프론트엔드 ⚛️

#178 feat: 카테고리에 따라 코드 에디터 하이라이팅이 다르게 되도록 구현
  packages/frontend/src/pages/DebugPage/index.tsx
  packages/frontend/src/pages/DebugPage/reducer.ts
  packages/frontend/src/pages/IntroPage/index.tsx
  packages/frontend/src/pages/ListPage/index.tsx
Labels: 개선 📈, 프론트엔드 ⚛️

#172 refactor: 전체적인 backend refactoring
  packages/backend/.env.sample
  packages/backend/src/app.ts
  packages/backend/src/controller/problemCodeController.ts
  packages/backend/src/controller/problemController.ts
  packages/backend/src/controller/statisticController.ts
  packages/backend/src/middleware/isLogin.ts
  packages/backend/src/middleware/setHeader.ts
  packages/backend/src/service/debugService.ts
  packages/backend/src/service/loginService.ts
  packages/backend/src/service/logoutService.ts
  packages/backend/src/service/problemCodeService.ts
  packages/backend/src/service/problemService.ts
  packages/backend/src/service/statisticService.ts
  packages/backend/src/service/submitService.ts
  packages/backend/src/setting/mongoConfig.ts
  packages/backend/src/setting/ormConfig.ts
  packages/backend/src/setting/sessionConfig.ts
  packages/backend/src/setting/socketConfig.ts
  packages/backend/src/util/common.ts
  packages/backend/src/util/constant.ts
  packages/backend/tsconfig.json
  packages/frontend/src/pages/DebugPage/index.tsx
  packages/types/src/entities.ts
Labels: 개선 📈, 중요도: 중, 백엔드 💻

#180 fix: socketConfig 내 user없는 소켓 disconnect 부분을 submit 이벤트 안으로 이동
  packages/backend/src/setting/socketConfig.ts
Labels: 개선 📈, 백엔드 💻

#181 chore: 로그인 버튼의 SVG 아이콘이 정상적으로 표시되지 않는 문제 수정
  packages/frontend/craco.config.js
  packages/frontend/package.json
  yarn.lock
Labels: 버그 🐛, 프론트엔드 ⚛️

#182 refactor: API 요청 코드에서 콜백 함수를 async / await 로 변경
  packages/frontend/src/App.tsx
  packages/frontend/src/pages/DebugPage/index.tsx
  packages/frontend/src/pages/DebugPage/message.ts
  packages/frontend/src/pages/IntroPage/index.tsx
  packages/frontend/src/pages/IntroPage/message.ts
  packages/frontend/src/pages/IntroPage/reducer.ts
  packages/frontend/src/pages/ListPage/index.tsx
Labels: 프론트엔드 ⚛️

#170 refactor: backend 테스트 코드 일부 작성
  package.json
  packages/backend/jest.config.ts
  packages/backend/package.json
  packages/backend/src/service/problemService.ts
  packages/backend/src/service/statisticService.ts
  packages/backend/src/setting/mongoConfig.ts
  packages/backend/src/test/beforeEach.ts
  packages/backend/src/test/problem.test.ts
  packages/backend/src/test/statistic.test.ts
  yarn.lock
Labels: 개선 📈, 중요도: 중, 백엔드 💻

#183 chore: 소켓 스트레스 테스트
  packages/frontend/stressTest/loadTest.js
Labels: 개선 📈, 백엔드 💻

#184 refactor: 부하 테스트 이후 socketConfig에서 test 이벤트 관련 제거
  packages/backend/src/setting/socketConfig.ts
Labels: 백엔드 💻

#185 feat: 소개 페이지 빈 통계 데이터 처리
  packages/frontend/src/pages/IntroPage/index.tsx
  packages/frontend/src/pages/IntroPage/message.ts
Labels: 프론트엔드 ⚛️

#186 fix: 누락된 return문 추가
  packages/backend/src/service/debugService.ts
  packages/types/src/entities.ts
Labels: 버그 🐛, 백엔드 💻

#188 fix: result의 const 키워드 제거
  packages/backend/src/service/debugService.ts
Labels: 백엔드 💻

#187 feat: 비동기 API 제공 및 콘솔 비동기 출력 지원
  packages/backend/package.json
  packages/backend/src/service/debugService.ts
  packages/frontend/src/App.css
  packages/frontend/src/components/Console.tsx
  packages/frontend/src/hooks/useSandbox/debug.ts
  packages/frontend/src/hooks/useSandbox/index.ts
  packages/frontend/src/hooks/useSandbox/sandbox.js
  packages/frontend/src/hooks/useSandbox/worker.js
  packages/frontend/src/pages/DebugPage/index.tsx
  packages/frontend/src/pages/WritePage/index.tsx
  yarn.lock
Labels: 개선 📈, 중요도: 상, 프론트엔드 ⚛️, 백엔드 💻

#190 feat: 타임아웃 이벤트 추가 및 에러 이벤트 전달 문제 수정
  packages/frontend/src/hooks/useSandbox/debug.ts
  packages/frontend/src/hooks/useSandbox/index.ts
Labels: 버그 🐛, 개선 📈, 프론트엔드 ⚛️

#189 feat: sinon 가이드라인 페이지 생성 및 가이드라인 페이지 분기 설정
  packages/frontend/src/App.tsx
  packages/frontend/src/assets/images/sinon.png
  packages/frontend/src/components/Modal/GuidelineCase.ts
  packages/frontend/src/pages/ChaiGuidePage/GuidelineCase.ts
  packages/frontend/src/pages/ChaiGuidePage/constant.ts
  packages/frontend/src/pages/ChaiGuidePage/index.tsx
  packages/frontend/src/pages/ChaiGuidePage/message.ts
  packages/frontend/src/pages/SinonGuidePage/GuidelineCase.ts
  packages/frontend/src/pages/SinonGuidePage/constant.ts
  packages/frontend/src/pages/SinonGuidePage/index.tsx
  packages/frontend/src/pages/SinonGuidePage/message.ts
  packages/frontend/src/pages/WritePage/index.tsx
  packages/types/src/entities.ts
Labels: 개선 📈, 프론트엔드 ⚛️

#191 feat: 문제 출제 전 코드 유효성 검증 로직 추가
  packages/frontend/src/pages/WritePage/constant.ts
  packages/frontend/src/pages/WritePage/index.tsx
  packages/frontend/src/pages/WritePage/message.ts
  packages/frontend/src/pages/WritePage/reducer.ts
Labels: 개선 📈, 프론트엔드 ⚛️

#192 fix: 코드 검증 로직 순서 변경
  packages/frontend/src/pages/WritePage/index.tsx
Labels: 버그 🐛, 프론트엔드 ⚛️

#194 fix: 결과 페이지 로그아웃 시 데이터가 들어가는 버그 및 에러 핸들링
  packages/frontend/src/pages/IntroPage/index.tsx
  packages/frontend/src/pages/ResultPage/index.tsx
  packages/frontend/src/pages/ResultPage/message.ts
  packages/frontend/src/pages/ResultPage/reducer.ts
Labels: 버그 🐛, 개선 📈, 프론트엔드 ⚛️

#195 deploy: [v0.0.6] 결과 페이지 버그 핫픽스 및 에러 핸들링
  packages/frontend/src/pages/IntroPage/index.tsx
  packages/frontend/src/pages/ResultPage/index.tsx
  packages/frontend/src/pages/ResultPage/message.ts
  packages/frontend/src/pages/ResultPage/reducer.ts
Labels: 배포 🚀

#197 chore: 마크다운 에디터가 의도한대로 동작하지 않는 문제를 수정
  packages/frontend/src/pages/WritePage/index.tsx
Labels: 버그 🐛, 프론트엔드 ⚛️

#196 chore: 레이아웃 관련 문제 수정
  packages/frontend/src/components/FullWidthViewer/styles.module.css
  packages/frontend/src/pages/DebugPage/index.tsx
  packages/frontend/src/pages/EditorPage/index.tsx
  packages/frontend/src/pages/WritePage/index.tsx
Labels: 버그 🐛, 프론트엔드 ⚛️

#199 fix: 출제 성공 메세지 변경
  packages/frontend/src/pages/WritePage/message.ts
Labels: 프론트엔드 ⚛️

#200 deploy: [v0.0.7] 에디터 설정 수정 및 출제 성공 시 메세지 변경
  packages/frontend/src/components/FullWidthViewer/styles.module.css
  packages/frontend/src/pages/DebugPage/index.tsx
  packages/frontend/src/pages/EditorPage/index.tsx
  packages/frontend/src/pages/WritePage/index.tsx
  packages/frontend/src/pages/WritePage/message.ts
Labels: 배포 🚀

#202 docs: readme업데이트
  README.md
Labels: 문서화 📄
