Repository boostcampwm-2021/web04-canyoufixme, pull requests merged in 2021-11, with the labels that each got.

#18 chore: 템플릿 문장 수정 및 prepare-commit-msg hook amend 옵션 문제 수정
  .gitmessage
  .husky/prepare-commit-msg
Labels: 버그

#28 chore: Typescript react 프로젝트 생성
  packages/frontend/.gitignore
  packages/frontend/README.md
  packages/frontend/package.json
  packages/frontend/public/favicon.ico
  packages/frontend/public/index.html
  packages/frontend/public/logo192.png
  packages/frontend/public/logo512.png
  packages/frontend/public/manifest.json
  packages/frontend/public/robots.txt
  packages/frontend/src/App.css
  packages/frontend/src/App.test.tsx
  packages/frontend/src/App.tsx
  packages/frontend/src/index.css
  packages/frontend/src/index.tsx
  packages/frontend/src/logo.svg
  packages/frontend/src/react-app-env.d.ts
  packages/frontend/src/reportWebVitals.ts
  packages/frontend/src/setupTests.ts
  packages/frontend/tsconfig.json
  packages/frontend/yarn.lock
  tsconfig.json
Labels: 중요도: 최상, 프론트엔드 ⚛️

#29 chore: CRA react 실행 안되는 이슈 해결(버전 이슈)
  package.json
  packages/frontend/yarn.lock
  yarn.lock
Labels: 버그 🐛, 프론트엔드 ⚛️

#31 feat: 라우터 설정
  packages/frontend/package.json
  packages/frontend/src/App.tsx
  packages/frontend/src/index.tsx
  packages/frontend/yarn.lock
Labels: 중요도: 상, 프론트엔드 ⚛️

#34 feat: 디버깅 페이지 에디터 추가 및 레이아웃 구성
  .eslintrc.json
  package.json
  packages/frontend/package.json
  packages/frontend/public/index.html
  packages/frontend/public/logo.png
  packages/frontend/public/manifest.json
  packages/frontend/public/robots.txt
  packages/frontend/src/App.css
  packages/frontend/src/App.tsx
  packages/frontend/src/assets/images/upscale.png
  packages/frontend/src/components/ButtonComponent.tsx
  packages/frontend/src/index.css
  packages/frontend/src/pages/DebugPage/debug.js
  packages/frontend/src/pages/DebugPage/index.tsx
  packages/frontend/src/pages/WritePage/index.tsx
  packages/styled/index.d.ts
  packages/styled/index.jsx
  packages/styled/package.json
  yarn.lock
Labels: 개선 📈, 중요도: 최상, 프론트엔드 ⚛️

#36 feat: 문제 리스트 페이지
  packages/frontend/src/App.css
  packages/frontend/src/App.tsx
  packages/frontend/src/pages/DebugPage/index.tsx
  packages/frontend/src/pages/ListPage/index.tsx
  src/app.ts
Labels: 개선 📈, 중요도: 상, 프론트엔드 ⚛️

#37 chore: Docker 개발 서버용 배포 이미지 설정 업데이트
  .dockerignore
  .gitignore
  Dockerfile
  README.md
  nginx.conf
  package.json
  packages/backend/package.json
  packages/backend/src/app.ts
  packages/backend/tsconfig.json
  packages/frontend/package.json
  tsconfig.json
  yarn.lock
Labels: 중요도: 최상, 백엔드

#39 feat: header, navbar css 작성 및 설정 파일 수정
  packages/frontend/package.json
  packages/frontend/src/App.tsx
  packages/frontend/src/components/NavLinkComponent.tsx
  packages/frontend/src/pages/WritePage/index.tsx
  packages/frontend/tsconfig.json
Labels: 개선 📈, 중요도: 중, 프론트엔드 ⚛️

#41 feat: 테스트 로직 구현 및 코드 에디터 prettier 적용
  .husky/prepare-commit-msg
  packages/backend/src/app.ts
  packages/frontend/package.json
  packages/frontend/src/components/NavLinkComponent.tsx
  packages/frontend/src/pages/DebugPage/debug.js
  packages/frontend/src/pages/DebugPage/index.tsx
  packages/frontend/src/pages/ListPage/index.tsx
  yarn.lock
Labels: 개선 📈, 중요도: 최상, 프론트엔드 ⚛️, 백엔드

#43 fix: 2번째 문제 expect 메소드 수정
  packages/backend/src/app.ts
Labels: 버그 🐛, 개선 📈

#56 chore: 커밋 메시지 형식 검사 및 Dockerfile 변경
  .husky/commit-msg
  Dockerfile
Labels: 개선 📈

#58 feat: 에디터 크기 조절 기능 구현
  packages/backend/.env.sample
  packages/backend/package.json
  packages/backend/src/app.ts
  packages/frontend/.env.sample
  packages/frontend/src/pages/DebugPage/index.tsx
  packages/styled/index.d.ts
  packages/styled/index.jsx
  packages/styled/tags.js
Labels: 개선 📈, 중요도: 상, 프론트엔드 ⚛️

#59 [v0.0.1] 2주차 스프린트 개발 후 merge/배포
  .dockerignore
  .eslintrc.json
  .gitignore
  .husky/commit-msg
  .husky/prepare-commit-msg
  Dockerfile
  README.md
  lerna.json
  nginx.conf
  package.json
  packages/backend/.env.sample
  packages/backend/package.json
  packages/backend/src/app.ts
  packages/backend/tsconfig.json
  packages/frontend/.env.sample
  packages/frontend/package.json
  packages/frontend/public/index.html
  packages/frontend/public/logo.png
  packages/frontend/public/manifest.json
  packages/frontend/public/robots.txt
  packages/frontend/src/App.css
  packages/frontend/src/App.tsx
  packages/frontend/src/assets/images/upscale.png
  packages/frontend/src/components/ButtonComponent.tsx
  packages/frontend/src/components/NavLinkComponent.tsx
  packages/frontend/src/index.css
  packages/frontend/src/index.tsx
  packages/frontend/src/pages/DebugPage/debug.js
  packages/frontend/src/pages/DebugPage/index.tsx
  packages/frontend/src/pages/ListPage/index.tsx
  packages/frontend/src/pages/WritePage/index.tsx
  packages/frontend/tsconfig.json
  packages/frontend/yarn.lock
  packages/styled/index.d.ts
  packages/styled/index.jsx
  packages/styled/package.json
  packages/styled/tags.js
  src/app.ts
  tsconfig.json
  yarn.lock
Labels: 배포 🚀

#60 Feat: MySQL과 TypeORM, MongoDB와 Mongoose 연동 및 테이블 생성
  .eslintrc.json
  packages/backend/.env.sample
  packages/backend/package.json
  packages/backend/settings/mongoConfig.ts
  packages/backend/settings/ormconfig.ts
  packages/backend/src/app.ts
  packages/backend/src/model/Problem.ts
  packages/backend/src/model/ProblemCode.ts
  packages/backend/src/model/SubmitCode.ts
  packages/backend/src/model/SubmitLog.ts
  packages/backend/src/model/User.ts
  packages/backend/tsconfig.json
  yarn.lock
Labels: 중요도: 최상, 백엔드 💻

#61 fix: ormComfig 파일 이름 변경
  packages/backend/settings/ormConfig.ts
Labels: 버그 🐛

#62 feat: 컴포넌트 스타일 상속 및 로그인페이지 레이아웃 구현
  packages/frontend/src/App.tsx
  packages/frontend/src/components/ButtonComponent.tsx
  packages/frontend/src/components/GitHubLoginButton/github.svg
  packages/frontend/src/components/GitHubLoginButton/index.tsx
  packages/frontend/src/components/GitHubLoginButton/octocat.svg
  packages/frontend/src/components/LoginButton.tsx
  packages/frontend/src/components/NavLinkComponent.tsx
  packages/frontend/src/components/TopNavLink.tsx
  packages/frontend/src/pages/LoginPage/index.tsx
  packages/styled/examples/extend-style/App.jsx
  packages/styled/examples/extend-style/index.html
  packages/styled/examples/extend-style/index.jsx
  packages/styled/examples/extend-style/package.json
  packages/styled/index.d.ts
  packages/styled/index.js
  packages/styled/index.jsx
Labels: 개선 📈, 중요도: 상, 프론트엔드 ⚛️

#64 feat: Iframe sandbox 적용
  packages/frontend/src/pages/DebugPage/debug.js
  packages/frontend/src/pages/DebugPage/debug.ts
  packages/frontend/src/pages/DebugPage/index.tsx
Labels: 개선 📈, 중요도: 최상, 프론트엔드 ⚛️

#65 feat: 문제와 문제 코드에 대한 API 개발
  packages/backend/src/app.ts
  packages/backend/src/controller/problemCodeController.ts
  packages/backend/src/controller/problemController.ts
  packages/backend/src/controller/problemsController.ts
  packages/backend/src/model/Problem.ts
  packages/backend/src/model/ProblemCode.ts
  packages/backend/src/model/SubmitCode.ts
  packages/backend/src/service/problemCodeService.ts
  packages/backend/src/service/problemService.ts
  packages/frontend/src/pages/DebugPage/debug.ts
  packages/frontend/src/pages/DebugPage/index.tsx
  packages/frontend/src/pages/ListPage/index.tsx
Labels: 개선 📈, 중요도: 상, 백엔드 💻

#67 fix: 커밋 amend 관련 문제 해결
  .husky/commit-msg
  .husky/prepare-commit-msg
Labels: 버그 🐛, 해결 완료 ✅

#68 feat: github oauth login, logout API 작성 및 연동
  packages/backend/.env.sample
  packages/backend/package.json
  packages/backend/settings/ormConfig.ts
  packages/backend/settings/sessionConfig.ts
  packages/backend/src/app.ts
  packages/backend/src/controller/loginController.ts
  packages/backend/src/controller/logoutController.ts
  packages/backend/src/service/loginService.ts
  packages/backend/src/service/logoutService.ts
  packages/frontend/.env.sample
  packages/frontend/src/App.tsx
  packages/frontend/src/components/GitHubLoginButton/github.svg
  packages/frontend/src/components/GitHubLoginButton/index.tsx
  packages/frontend/src/components/GitHubLoginButton/octocat.svg
  packages/frontend/src/components/LoginButton.tsx
  packages/frontend/src/pages/LoginPage/index.tsx
  packages/styled/index.d.ts
  yarn.lock
Labels: 중요도: 최상, 프론트엔드 ⚛️, 백엔드 💻

#70 feat: 문제 출제(등록) API 개발
  packages/backend/src/app.ts
  packages/backend/src/controller/problemController.ts
  packages/backend/src/service/loginService.ts
  packages/backend/src/service/problemService.ts
Labels: 중요도: 상, 백엔드 💻

#71 feat: 문제 출제 페이지
  packages/frontend/package.json
  packages/frontend/src/App.css
  packages/frontend/src/App.tsx
  packages/frontend/src/components/Button.tsx
  packages/frontend/src/components/FullWidthViewer.tsx
  packages/frontend/src/components/TestCodeEditor.tsx
  packages/frontend/src/components/TestCodeViewer.tsx
  packages/frontend/src/hooks/useLogin.ts
  packages/frontend/src/pages/DebugPage/index.tsx
  packages/frontend/src/pages/EditorPage/index.tsx
  packages/frontend/src/pages/WritePage/index.tsx
  packages/frontend/tsconfig.json
  packages/styled/index.js
Labels: 개선 📈, 중요도: 최상, 프론트엔드 ⚛️

#73 chore: Dockerfile multi-stage build로 변경
  Dockerfile
  nginx.conf
  package.json
Labels: 백엔드 💻, 배포 🚀

#77 chore: 백엔드 추가에 대응한 도커 이미지 빌드 옵션 개선
  .dockerignore
  Dockerfile
Labels: 배포 🚀

#78 chore: 자동 배포 yml 파일 추가
  .github/workflows/deploy.yml
Labels: 배포 🚀

#80 chore: 자동 배포 yml 파일 추가
  .github/workflows/deploy.yml
Labels: 배포 🚀

#81 fix: 자동 배포 yml 파일 root 경로 추가
  .github/workflows/deploy.yml
Labels: 버그 🐛

#82 fix: Dockerfile 내의 다중 COPY 시 경로 설정 변경
  Dockerfile
Labels: 버그 🐛

#83 chore: 새로고침 시의 nginx 라우팅 주소 404 오류 방지
  nginx.conf
Labels: 배포 🚀

#84 fix: backend 내 settings 폴더 위치를 src 폴더 하위로 변경
  packages/backend/src/app.ts
  packages/backend/src/service/problemCodeService.ts
  packages/backend/src/service/problemService.ts
  packages/backend/src/settings/mongoConfig.ts
  packages/backend/src/settings/ormConfig.ts
  packages/backend/src/settings/sessionConfig.ts
  packages/backend/tsconfig.json
Labels: 개선 📈, 백엔드 💻

#85 chore: ormconfig entities 배열 값을 import 객체 값으로 수정
  packages/backend/src/settings/ormConfig.ts
Labels: 개선 📈, 백엔드 💻

#87 feat: debounce 패키지 추가
  packages/debounce/examples/index.html
  packages/debounce/examples/index.js
  packages/debounce/index.d.ts
  packages/debounce/index.js
  packages/debounce/package.json
Labels: 개선 📈, 중요도: 상, 프론트엔드 ⚛️

#88 chore: 백엔드 배포환경 트랜스파일 빌드 적용
  Dockerfile
  packages/backend/package.json
  packages/backend/tsconfig.json
Labels: 개선 📈, 백엔드 💻, 배포 🚀

#90 fix: Backtick 입력시 동작하지 않는 문제 수정 및 iframe 화면 노출 방지
  packages/frontend/src/pages/DebugPage/debug.ts
Labels: 버그 🐛, 프론트엔드 ⚛️

#91 feat: 문제 리스트 API에 offset과 limit 쿼리 적용
  packages/backend/src/service/problemService.ts
Labels: 개선 📈, 백엔드 💻

#97 chore: 도커 이미지 경량화 작업
  Dockerfile
  nginx.conf
  package.json
  packages/frontend/package.json
Labels: 개선 📈, 배포 🚀

#98 fix: 불필요한 컬럼이 노출되지 않도록 조치
  packages/backend/src/model/User.ts
Labels: 백엔드 💻

#99 feat: 문제 리스트 페이지 무한 스크롤 기능 추가
  packages/frontend/src/pages/ListPage/index.tsx
  packages/frontend/src/pages/ListPage/reducer.ts
Labels: 개선 📈, 중요도: 최상, 프론트엔드 ⚛️

#100 feat: 출제 페이지 제목 입력창 추가 및 레이아웃 관련 UX 개선
  packages/frontend/src/App.css
  packages/frontend/src/components/FullWidthInput.tsx
  packages/frontend/src/components/FullWidthViewer/index.tsx
  packages/frontend/src/components/FullWidthViewer/styles.module.css
  packages/frontend/src/components/TestCodeEditor.tsx
  packages/frontend/src/components/TestCodeViewer.tsx
  packages/frontend/src/pages/DebugPage/index.tsx
  packages/frontend/src/pages/EditorPage/index.tsx
  packages/frontend/src/pages/ListPage/index.tsx
  packages/frontend/src/pages/WritePage/index.tsx
  packages/styled/index.d.ts
  packages/styled/index.js
  packages/styled/tags.js
Labels: 개선 📈, 프론트엔드 ⚛️

#103 chore: submitCode, submitLog 모델 수정
  packages/backend/src/model/SubmitCode.ts
  packages/backend/src/model/SubmitLog.ts
Labels: 개선 📈, 백엔드 💻

#102 feat: Modal 레이아웃 생성 및 로그아웃 기능에 Modal 적용
  .gitignore
  packages/frontend/package.json
  packages/frontend/src/App.tsx
  packages/frontend/src/components/Modal/ConfirmModal.tsx
  packages/frontend/src/components/Modal/MessageModal.tsx
  packages/frontend/src/components/Modal/Modal.tsx
  packages/frontend/src/components/Modal/ModalButton.tsx
  yarn.lock
Labels: 개선 📈, 중요도: 중, 프론트엔드 ⚛️

#106 feat: socket 연동 및 workerpool 적용(동시성 채점 구현)
  packages/backend/package.json
  packages/backend/src/app.ts
  packages/backend/src/controller/submitController.ts
  packages/backend/src/service/debugService.ts
  packages/backend/src/service/submitService.ts
  packages/backend/src/settings/socketConfig.ts
  packages/frontend/package.json
  packages/frontend/src/pages/DebugPage/index.tsx
  yarn.lock
Labels: 중요도: 최상, 백엔드 💻

#107 fix: login session 쿠키(isLogin)에 max-age 추가 및 logout 시 로직 일부 수정
  packages/backend/src/service/loginService.ts
  packages/backend/src/service/logoutService.ts
Labels: 개선 📈, 백엔드 💻

#108 fix: Docker 이미지 내에서의 경로 차이로 인한 실행 오류 수정
  packages/backend/src/settings/socketConfig.ts
  yarn.lock
Labels: 버그 🐛, 백엔드 💻

#109 fix: 출제 페이지에서 테스트 코드를 추가할 때 높이가 증가하는 현상 수정
  packages/frontend/src/pages/WritePage/index.tsx
Labels: 버그 🐛, 프론트엔드 ⚛️

#111 feat: 페이지 별 Modal 적용
  packages/frontend/src/App.tsx
  packages/frontend/src/assets/images/loading.gif
  packages/frontend/src/components/Modal/ConfirmModal.tsx
  packages/frontend/src/components/Modal/LoadingModal.tsx
  packages/frontend/src/pages/DebugPage/index.tsx
  packages/frontend/src/pages/ListPage/index.tsx
  packages/frontend/src/pages/LoginPage/index.tsx
  packages/frontend/src/pages/WritePage/index.tsx
Labels: 개선 📈, 프론트엔드 ⚛️

#116 fix: worker_thread 개수 5개로 설정
  packages/backend/src/settings/socketConfig.ts
Labels: 버그 🐛, 개선 📈, 백엔드 💻

#115 docs: README 업데이트
  README.md
  packages/styled/README.md
Labels: 문서화 📄

#118 fix: 샌드박스 매개변수가 minify 되어 오류가 발생하는 문제 수정
  packages/frontend/craco.config.js
  packages/frontend/package.json
  packages/frontend/src/pages/DebugPage/sandbox.js
  yarn.lock
Labels: 버그 🐛, 배포 🚀

#113 fix: Modal 중복 제거 및 이동 시 닫기 버튼 제거
  packages/frontend/src/components/Modal/MessageModal.tsx
  packages/frontend/src/pages/WritePage/index.tsx
Labels: 버그 🐛, 프론트엔드 ⚛️

#119 feat: Timeout 에러에 대한 Modal 처리
  packages/frontend/src/pages/DebugPage/index.tsx
Labels: 개선 📈, 프론트엔드 ⚛️

#120 fix: Message Modal 닫기 버튼이 사라진 현상 수정
  packages/frontend/src/App.tsx
  packages/frontend/src/pages/DebugPage/index.tsx
  packages/frontend/src/pages/WritePage/index.tsx
Labels: 버그 🐛

#124 docs: readme 내용 수정
  README.md
Labels: 문서화 📄

#126 chore: Husky 커밋 관련 훅 개선
  .husky/commit-msg
  .husky/pre-commit
Labels: 개선 📈

#125 refactor: http api 방식에서 소켓 통신 방식으로 채점 결과를 저장하도록 방식 변경
  packages/backend/src/app.ts
  packages/backend/src/controller/submitController.ts
  packages/backend/src/service/submitService.ts
  packages/backend/src/service/userService.ts
  packages/backend/src/settings/socketConfig.ts
  packages/frontend/src/pages/DebugPage/index.tsx
Labels: 개선 📈, 중요도: 상, 백엔드 💻

#127 chore: HTTPS 적용에 따른 변경사항
  .dockerignore
  .github/workflows/dev-deploy.yml
  Dockerfile
  README.md
  nginx.conf.template
Labels: 해결 완료 ✅, 배포 🚀

#128 fix: 로그인 상태가 전역 상태로 관리되도록 수정
  packages/frontend/src/App.tsx
  packages/frontend/src/contexts/LoginContext.ts
  packages/frontend/src/hooks/useLogin.ts
  packages/frontend/src/pages/WritePage/index.tsx
Labels: 버그 🐛, 프론트엔드 ⚛️

#129 refactor: 소켓 통신을 이용하여 실시간으로 테스트 결과값 전달
  packages/backend/src/service/debugService.ts
  packages/backend/src/settings/socketConfig.ts
Labels: 개선 📈, 백엔드 💻

#130 feat: 테스트케이스 가이드라인 추가
  packages/frontend/src/components/Modal/GuideModal.tsx
  packages/frontend/src/components/Modal/GuidelineCase.ts
  packages/frontend/src/pages/GuidePage/GuidelineCase.ts
  packages/frontend/src/pages/GuidePage/index.tsx
Labels: 개선 📈, 프론트엔드 ⚛️

#131 Refactor: Socket을 전역 상태로 관리하도록 수정
  packages/frontend/src/App.tsx
  packages/frontend/src/contexts/SocketContext.ts
  packages/frontend/src/pages/DebugPage/index.tsx
Labels: 개선 📈, 프론트엔드 ⚛️

#133 feat: 에디터 수정시 페이지 이동 방지 기능 추가
  packages/frontend/src/hooks/useBlockUnload.ts
  packages/frontend/src/pages/DebugPage/index.tsx
  packages/frontend/src/pages/DebugPage/reducer.ts
  packages/frontend/src/pages/WritePage/index.tsx
Labels: 개선 📈, 프론트엔드 ⚛️

#135 feat: 결과 페이지 생성
  packages/backend/src/service/debugService.ts
  packages/backend/src/settings/socketConfig.ts
  packages/frontend/src/App.tsx
  packages/frontend/src/components/ResultViewer.tsx
  packages/frontend/src/pages/ResultPage/enums.ts
  packages/frontend/src/pages/ResultPage/index.tsx
Labels: 개선 📈, 프론트엔드 ⚛️

#136 fix: debug 페이지 history 중복 선언 제거 및 testCode 값 지정
  packages/frontend/src/pages/DebugPage/index.tsx
Labels: 개선 📈, 프론트엔드 ⚛️

#137 feat: 페이지 간 에디터 크기 동기화 기능 구현
  packages/frontend/craco.config.js
  packages/frontend/package.json
  packages/frontend/src/pages/EditorPage/index.tsx
  packages/frontend/src/pages/EditorPage/module.d.ts
  packages/frontend/src/pages/EditorPage/sync.worker.js
  packages/frontend/tsconfig.json
  yarn.lock
Labels: 개선 📈, 프론트엔드 ⚛️

#144 fix: API 도메인 변경에 따른 로그인 문제 해결
  packages/backend/src/app.ts
  packages/backend/src/service/loginService.ts
  packages/backend/src/service/logoutService.ts
Labels: 버그 🐛, 백엔드 💻, 배포 🚀

#138 chore: main-branch github action 작성
  .github/workflows/main-deploy.yml
Labels: 배포 🚀

#139 feat: 문제 출제 페이지 업데이트
  packages/frontend/src/App.tsx
  packages/frontend/src/components/FullWidthDiv/index.tsx
  packages/frontend/src/components/Modal/GuideModal.tsx
  packages/frontend/src/components/Modal/SelectModal.tsx
  packages/frontend/src/components/TestCodeEditor.tsx
  packages/frontend/src/components/TestCodeViewer.tsx
  packages/frontend/src/pages/WriteEditorPage/index.tsx
  packages/frontend/src/pages/WritePage/constant.ts
  packages/frontend/src/pages/WritePage/index.tsx
Labels: 개선 📈, 프론트엔드 ⚛️

#141 fix: Placeholder를 escape 처리 하도록 수정
  packages/frontend/src/pages/DebugPage/debug.ts
  packages/frontend/src/pages/DebugPage/worker.js
Labels: 버그 🐛, 프론트엔드 ⚛️

#140 feat: 백엔드 채점 로직 구현 및 `vm2` 적용
  packages/backend/package.json
  packages/backend/src/service/debugService.ts
  packages/backend/src/settings/socketConfig.ts
  yarn.lock
Labels: 개선 📈, 중요도: 최상, 백엔드 💻

#146 fix: 세션 관련 프록시 설정 추가
  nginx.conf.template
  packages/backend/src/app.ts
  packages/backend/src/settings/socketConfig.ts
  packages/frontend/src/contexts/SocketContext.ts
Labels: 버그 🐛, 백엔드 💻, 배포 🚀

#148 fix: 잘못된 Nginx 설정 문법 수정
  nginx.conf.template
Labels: 버그 🐛, 배포 🚀

#147 feat: 메인 페이지에서 사용할 데이터에 대한 api 개발
  packages/backend/src/app.ts
  packages/backend/src/controller/statisticController.ts
  packages/backend/src/service/statisticService.ts
Labels: 중요도: 상, 백엔드 💻

#149 feat: 404 페이지 추가
  packages/frontend/src/App.tsx
  packages/frontend/src/assets/images/404.png
  packages/frontend/src/pages/NotFoundPage/index.tsx
Labels: 개선 📈, 프론트엔드 ⚛️

#150 feat: 소개 페이지 레이아웃 생성
  packages/frontend/src/App.tsx
  packages/frontend/src/assets/images/logo.svg
  packages/frontend/src/pages/IntroPage/index.tsx
Labels: 개선 📈, 프론트엔드 ⚛️

#151 refactor: statistic에 대한 데이터를 변환하는 로직을 프론트엔드에서 백엔드로 이동
  packages/backend/src/service/statisticService.ts
  packages/frontend/src/pages/IntroPage/index.tsx
Labels: 개선 📈, 백엔드 💻

#152 feat: 제출 버튼을 눌렀을때 이동 방지를 해제하도록 수정
  packages/frontend/src/hooks/useBlockUnload.ts
  packages/frontend/src/pages/DebugPage/index.tsx
  packages/frontend/src/pages/WritePage/index.tsx
Labels: 개선 📈, 프론트엔드 ⚛️

#153 feat: 문제 풀이 제출 시 로그인 여부 확인
  packages/frontend/src/pages/DebugPage/index.tsx
Labels: 개선 📈, 프론트엔드 ⚛️

#155 chore!: 프론트엔드 테스트로직 제거 및 콘솔 출력 구현
  packages/frontend/src/pages/DebugPage/debug.ts
  packages/frontend/src/pages/DebugPage/index.tsx
  packages/frontend/src/pages/DebugPage/sandbox.js
  packages/frontend/src/pages/DebugPage/worker.js
Labels: 프론트엔드 ⚛️

#158 feat: 출제 페이지 실행 기능 추가
  packages/frontend/src/components/Console.tsx
  packages/frontend/src/hooks/useSandbox/debug.ts
  packages/frontend/src/hooks/useSandbox/index.ts
  packages/frontend/src/hooks/useSandbox/sandbox.js
  packages/frontend/src/hooks/useSandbox/worker.js
  packages/frontend/src/pages/DebugPage/index.tsx
  packages/frontend/src/pages/WritePage/index.tsx
Labels: 중요도: 최상, 프론트엔드 ⚛️

#159 chore: PM2 설정 및 모니터링 KEY 추가
  .github/workflows/main-deploy.yml
  Dockerfile
  packages/backend/package.json
Labels: 배포 🚀

#160 deploy: [v0.0.3] PM2 설정 및 출제 페이지 실행 코드 적용
  .github/workflows/main-deploy.yml
  Dockerfile
  packages/backend/package.json
  packages/frontend/src/components/Console.tsx
  packages/frontend/src/hooks/useSandbox/debug.ts
  packages/frontend/src/hooks/useSandbox/index.ts
  packages/frontend/src/hooks/useSandbox/sandbox.js
  packages/frontend/src/hooks/useSandbox/worker.js
  packages/frontend/src/pages/DebugPage/index.tsx
  packages/frontend/src/pages/WritePage/index.tsx
Labels: 배포 🚀

#162 deploy: [v0.0.4] dockerfile 내 타입 수정
  Dockerfile
Labels: 개선 📈, 배포 🚀

#163 feat: 문제 풀이 및 제출 페이지의 제출 버튼에 디바운스 적용
  packages/frontend/src/pages/DebugPage/index.tsx
  packages/frontend/src/pages/WritePage/index.tsx
Labels: 개선 📈, 프론트엔드 ⚛️

#164 fix: SharedWorker 미지원 브라우저에 대한 예외처리 추가
  packages/frontend/src/pages/EditorPage/index.tsx
Labels: 버그 🐛, 프론트엔드 ⚛️

#165 refactor: 상수 및 메세지를 페이지 파일로부터 분리
  packages/frontend/src/App.tsx
  packages/frontend/src/components/Modal/ConfirmModal.tsx
  packages/frontend/src/components/Modal/MessageModal.tsx
  packages/frontend/src/components/TestCodeEditor.tsx
  packages/frontend/src/pages/DebugPage/index.tsx
  packages/frontend/src/pages/DebugPage/message.ts
  packages/frontend/src/pages/WritePage/constant.ts
  packages/frontend/src/pages/WritePage/index.tsx
  packages/frontend/src/pages/WritePage/message.ts
Labels: 프론트엔드 ⚛️

#166 refactor: Modal 상태 관리를 Reducer로 수정
  packages/frontend/src/App.tsx
  packages/frontend/src/components/Modal/ConfirmModal.tsx
  packages/frontend/src/components/Modal/GuideModal.tsx
  packages/frontend/src/components/Modal/MessageModal.tsx
  packages/frontend/src/components/Modal/Modal.tsx
  packages/frontend/src/components/Modal/ModalType.ts
  packages/frontend/src/components/Modal/SelectModal.tsx
  packages/frontend/src/components/TestCodeEditor.tsx
  packages/frontend/src/pages/DebugPage/index.tsx
  packages/frontend/src/pages/DebugPage/message.ts
  packages/frontend/src/pages/DebugPage/reducer.ts
  packages/frontend/src/pages/WritePage/constant.ts
  packages/frontend/src/pages/WritePage/index.tsx
  packages/frontend/src/pages/WritePage/reducer.ts
Labels: 프론트엔드 ⚛️

#167 refactor: 공통 타입 분리 및 인터페이스 추가
  .eslintrc.json
  Dockerfile
  packages/backend/package.json
  packages/backend/src/model/Problem.ts
  packages/backend/src/model/ProblemCode.ts
  packages/backend/src/model/SubmitCode.ts
  packages/backend/src/model/SubmitLog.ts
  packages/backend/src/model/User.ts
  packages/backend/src/service/statisticService.ts
  packages/backend/src/service/submitService.ts
  packages/frontend/package.json
  packages/frontend/src/components/Modal/GuideModal.tsx
  packages/frontend/src/components/Modal/GuidelineCase.ts
  packages/frontend/src/components/ResultViewer.tsx
  packages/frontend/src/pages/DebugPage/reducer.ts
  packages/frontend/src/pages/GuidePage/GuidelineCase.ts
  packages/frontend/src/pages/GuidePage/index.tsx
  packages/frontend/src/pages/IntroPage/index.tsx
  packages/frontend/src/pages/ListPage/index.tsx
  packages/frontend/src/pages/ListPage/reducer.ts
  packages/frontend/src/pages/ResultPage/index.tsx
  packages/frontend/src/pages/WritePage/index.tsx
  packages/types/package.json
  packages/types/src/entities.ts
  packages/types/src/enums.ts
  packages/types/src/index.ts
  packages/types/tsconfig.json
  yarn.lock
Labels: 프론트엔드 ⚛️, 백엔드 💻

#168 chore: 커밋 제목의 `%` 문자를 포맷문자로 인식하지 않도록 수정
  .husky/prepare-commit-msg
Labels: 버그 🐛
